language: csharp
branches:
  only:
    - master
    - dev
    - ci-support
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
os:
  - linux
# .NET CLI require Ubuntu 14.04
dist: trusty
services:
  - docker
# Ensure that .NET Core is installed
dotnet: 1.0.1
# Ensure Mono is installed
mono: latest
env:
  global:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    # Disable sending usage data to Microsoft
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
    # Sets the DOCKER_USERNAME and DOCKER_PASSWORD variables
    # More info: https://docs.travis-ci.com/user/environment-variables/
    - secure: "OtM8vx5mqfULIoJoHVijqilQTV92uSfZDMGlAvGtIBQJPvkjvS2lJbMw0O4YCy1HqRbAp4LtSqm9N0VzEmsc0U1tNZ+8yJMkE7N/vuK8vC+9JTsdnEuvfnXooUU758J3G20MNA8ST7rkq0tShO6xrFHBRysYd3kJ4kaE927SUiJeZvBwC+kGan56enz+YOBtAWaK+Wjs0Kpz+eYnBt6BtbWYvvhLvj5W71I7D2a8WcMM4S7Q/qV0HOaNO5tSqQHxp0svws3CsMZdlYP8MEI71JW9uiHbDjzljmPeUdzRxf71koDHYmFIM+rfV6m7KeXAM7r4uitTHBtuJCQek1GzbESU4SoMWoQAkIlYZckkPJ0yCxANQXFHR5yhcm1Jr6UvdATJkU6bObTm2OPJc/LMzjvnJqspLQg5/P5jwQJnFw+QYawuMmUNIala0Y0xBmfuA3E/md748zUl7Z8WOxIQRVpZ1exW/96LTDtgDo/trA+hfSV+DDNQblVh5qBR0DL5Qul69jbTnIZelIhfXhEL1droKm/O3GkoNY7pRrKCm7JWp8yDeq3aVS4BveeWBXjNoDvW9IQSfpuYdq3cfQ6XnMIL15jJlZ8oJGtNmCrDxxrkAnrI6tSvzM9zsheb1CPSOqOiuIJIlyJdFUjwZJmMTYtZrvRuHGI6bnGXVtm8OJU="
    - secure: "rQbzcQR27zCEx44QXX5Pk6o8OdAMlx8bEXk5Rt3RJPvzMRwzTTIa1OUC/XNvU2K6IISpQJtSzVdI+kuHcPMn3SYqG1XMjFZi/JUeWMiJ1coFMZIkgGPlbtI9bsVpZdQocjVLdWuiQuXhBzmd6+9F2Ca2eAylO0yS9wUcq9LtSglHE+NKWU5l8MbJcfuwFjbvR9jPHmGSPQTpzSIs3BVfBDuBjYK6QOYB4d5M1KSiMIJDGNze04VrDmvyXFI1GKbWiX2yc6wNdvyS+UfzoQ0dKnOBPTxrCGCURNsNkC0tH3Huj4y/YKY+csDGAbgEPgpkDr6xYZiU08tyBXezIw+39ACU0iTOZPjXUrjNoTZc7pQkFxuwlkv68P/QMMl/s6SHBfuD82LnmDnjDBQCwXp+TjG/a8Bw07Xvd+t124SKVrTgLe/txogTrzd9Qb0VjrzGeH7jw1/xNR5EXrNXDFbO7KlOeZH4qgFf0ofwvdNahkgwQAm7cTt/L0pt2Y0Si6mZ6nTqj8NwA/S37MYSJUvp9AfXLprL1HZIUUy12R4M0p3L1qZzCwdIJz92YcMI+8LJsiWRPi+PVcSkSJAbNhEqIpOuSVje/nSbp5y/P74JP0wwfj9W/jTCPSfvcSWlRjBcCPi/fNjk30AFEh3ED8WDMfq+bC/rM3xwt9gaJ3NhJ9M="
script:
  - ./build.sh -t TravisCI
before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
deploy:
  - provider: script
    skip_cleanup: true
    script: ./build.sh -t Docker-Build-AND-Push -dockerPushCurrentVersion -dockerPushAdditionalTag=latest
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./build.sh -t Docker-Build-AND-Push -dockerPushAdditionalTag=beta
    on:
      branch: master
      tags: false
after_deploy:
  - docker logout